In [55]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [56]:
data=pd.read_csv('/home/bibek/Desktop/pandas_practice_realDataset/datasets/netflix_titles.csv',
    encoding='latin1')

In [57]:
data.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [58]:
data.shape

(8807, 12)

In [59]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [60]:
data.describe()

       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

In [61]:
#number of movies
data[data['type']=='Movie']['show_id'].count()

np.int64(6131)

In [62]:
#number of tv shows
data[data['type']=='TV Shows']['show_id'].count()

np.int64(0)

In [63]:
#country producing most contenct
data.groupby('country')['show_id'].count().sort_values(ascending=False).index[0]

'United States'

In [64]:
#director with most titles
data.groupby('director')['title'].count().sort_values(ascending=False).index[0]

'Rajiv Chilaka'

In [65]:
movies = data[data['type'] == 'Movie'].copy()

movies['duration_min'] = (
    movies['duration']
    .str.extract('(\d+)')[0]
    .astype('Int64')
)
# movies[movies['duration'].str.extract(r'(\d+)')[0].isna()][['title', 'duration']]
# movies['duration'].isna().sum()
int(movies['duration_min'].max())

312

In [66]:
### most common genre
data['listed_in'].str.split(', ').explode().value_counts().index[0]
#str.split(', ') splits each genre
#explode() creates a row for each genre
# value_counts() counts repeatetion of each genre

'International Movies'

In [67]:
data['year']=pd.to_datetime(movies['date_added']).dt.year
movies=data[data['type']=='Movie'].copy()
movies_per_year=(
    movies.groupby('year')['title']
 .count()
 .reset_index(name='Number of Movies')
)
movies_per_year

      year  Number of Movies
0   2008.0                 1
1   2009.0                 2
2   2010.0                 1
3   2011.0                13
4   2012.0                 3
5   2013.0                 6
6   2014.0                19
7   2015.0                56
8   2016.0               253
9   2017.0               839
10  2018.0              1237
11  2019.0              1424
12  2020.0              1284
13  2021.0               993

In [76]:
tv_shows=data[data['type']=='TV Show'].copy()
tv_shows['date_added']=tv_shows['date_added'].str.strip()
tv_shows['added_year']=pd.to_datetime(tv_shows['date_added'],errors='coerce').dt.year
tv_shows = tv_shows.dropna(subset=['added_year'])
tv_shows['added_year']=tv_shows['added_year'].astype(int)
tv_shows.groupby('added_year')['title'].count()

added_year
2008      1
2013      5
2014      5
2015     26
2016    176
2017    349
2018    412
2019    592
2020    595
2021    505
Name: title, dtype: int64

In [77]:
data.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,year
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",2021.0
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",NaN
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,NaN
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",NaN
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,NaN

In [ ]:
#top actors
data['cast'].str.split(', ').explode().value_counts().head(5)

cast
Anupam Kher         43
Shah Rukh Khan      35
Julie Tejwani       33
Takahiro Sakurai    32
Naseeruddin Shah    32
Name: count, dtype: int64

In [99]:
# movies['duration']=movies['duration'].str.extract(r'(\d+)')[0].astype('Int64')
float(movies['duration'].mean())

99.57718668407311